# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import product_info_pb2 as proto_dot_product__info__pb2


class ProductInfoStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.addProduct = channel.unary_unary(
        '/ecommerce.ProductInfo/addProduct',
        request_serializer=proto_dot_product__info__pb2.Product.SerializeToString,
        response_deserializer=proto_dot_product__info__pb2.ProductID.FromString,
        )
    self.getProduct = channel.unary_unary(
        '/ecommerce.ProductInfo/getProduct',
        request_serializer=proto_dot_product__info__pb2.ProductID.SerializeToString,
        response_deserializer=proto_dot_product__info__pb2.Product.FromString,
        )


class ProductInfoServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def addProduct(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getProduct(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ProductInfoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'addProduct': grpc.unary_unary_rpc_method_handler(
          servicer.addProduct,
          request_deserializer=proto_dot_product__info__pb2.Product.FromString,
          response_serializer=proto_dot_product__info__pb2.ProductID.SerializeToString,
      ),
      'getProduct': grpc.unary_unary_rpc_method_handler(
          servicer.getProduct,
          request_deserializer=proto_dot_product__info__pb2.ProductID.FromString,
          response_serializer=proto_dot_product__info__pb2.Product.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ecommerce.ProductInfo', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
