// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/product_info.proto

package product_info

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Product struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_bca18e0841a4a514, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Product)(nil), "ecommerce.Product")
}

func init() { proto.RegisterFile("proto/product_info.proto", fileDescriptor_bca18e0841a4a514) }

var fileDescriptor_bca18e0841a4a514 = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8e, 0xbf, 0x6a, 0xc3, 0x30,
	0x10, 0xc6, 0xb1, 0x5b, 0x5a, 0x7c, 0x86, 0x0e, 0x9a, 0x84, 0x29, 0xc5, 0x74, 0xea, 0x24, 0x43,
	0xbb, 0x77, 0xef, 0xd4, 0x90, 0x40, 0xd6, 0x20, 0x4b, 0x67, 0x21, 0xb0, 0x75, 0x42, 0x96, 0xc9,
	0x53, 0xe4, 0x9d, 0x43, 0x64, 0x3b, 0x64, 0x08, 0xd9, 0x8e, 0xdf, 0xf7, 0xe7, 0x3e, 0xe0, 0x3e,
	0x50, 0xa4, 0xc6, 0x07, 0xd2, 0x93, 0x8a, 0x07, 0xeb, 0x3a, 0x12, 0x09, 0xb1, 0x02, 0x15, 0x0d,
	0x03, 0x06, 0x85, 0xd5, 0x87, 0x21, 0x32, 0x3d, 0x36, 0x49, 0x68, 0xa7, 0xae, 0x39, 0x06, 0xe9,
	0x3d, 0x86, 0x71, 0xb6, 0x7e, 0xfe, 0xc3, 0xeb, 0x66, 0x2e, 0x60, 0x6f, 0x90, 0x5b, 0xcd, 0xb3,
	0x3a, 0xfb, 0x2a, 0xb6, 0xb9, 0xd5, 0x8c, 0xc1, 0xb3, 0x93, 0x03, 0xf2, 0x3c, 0x91, 0x74, 0xb3,
	0x1a, 0x4a, 0x8d, 0xa3, 0x0a, 0xd6, 0x47, 0x4b, 0x8e, 0x3f, 0x25, 0xe9, 0x16, 0x7d, 0x9f, 0x32,
	0x28, 0x97, 0xc6, 0x3f, 0xd7, 0x11, 0xfb, 0x05, 0x90, 0x5a, 0xaf, 0x3f, 0x98, 0xb8, 0x4e, 0x13,
	0x0b, 0xab, 0xde, 0xc5, 0xbc, 0x51, 0xac, 0x1b, 0xc5, 0x2e, 0x06, 0xeb, 0xcc, 0x5e, 0xf6, 0x13,
	0x5e, 0xf2, 0x06, 0xe3, 0x9a, 0x7f, 0xe8, 0xad, 0xee, 0xb4, 0xb7, 0x2f, 0xc9, 0xf9, 0x73, 0x0e,
	0x00, 0x00, 0xff, 0xff, 0xcd, 0x0b, 0x13, 0x19, 0x2e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProductInfoClient is the client API for ProductInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductInfoClient interface {
	AddProduct(ctx context.Context, in *Product, opts ...grpc.CallOption) (*wrappers.StringValue, error)
	GetProduct(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*Product, error)
}

type productInfoClient struct {
	cc *grpc.ClientConn
}

func NewProductInfoClient(cc *grpc.ClientConn) ProductInfoClient {
	return &productInfoClient{cc}
}

func (c *productInfoClient) AddProduct(ctx context.Context, in *Product, opts ...grpc.CallOption) (*wrappers.StringValue, error) {
	out := new(wrappers.StringValue)
	err := c.cc.Invoke(ctx, "/ecommerce.ProductInfo/addProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productInfoClient) GetProduct(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*Product, error) {
	out := new(Product)
	err := c.cc.Invoke(ctx, "/ecommerce.ProductInfo/getProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductInfoServer is the server API for ProductInfo service.
type ProductInfoServer interface {
	AddProduct(context.Context, *Product) (*wrappers.StringValue, error)
	GetProduct(context.Context, *wrappers.StringValue) (*Product, error)
}

func RegisterProductInfoServer(s *grpc.Server, srv ProductInfoServer) {
	s.RegisterService(&_ProductInfo_serviceDesc, srv)
}

func _ProductInfo_AddProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Product)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductInfoServer).AddProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ecommerce.ProductInfo/AddProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductInfoServer).AddProduct(ctx, req.(*Product))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductInfo_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductInfoServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ecommerce.ProductInfo/GetProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductInfoServer).GetProduct(ctx, req.(*wrappers.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductInfo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ecommerce.ProductInfo",
	HandlerType: (*ProductInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "addProduct",
			Handler:    _ProductInfo_AddProduct_Handler,
		},
		{
			MethodName: "getProduct",
			Handler:    _ProductInfo_GetProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/product_info.proto",
}
